services:

  app-user-service:
    container_name: app-user-service
    build:
      context: .
      dockerfile: Dockerfile
    restart: no
    ports:
      - 8082:8082
    environment:
      HOST_DB: userdb
      PORT_DB: 5433
      NAME_DB: ${NAME_DB}
      USER_DB: ${USER_DB}
      PASSWORD_DB: ${PASSWORD_DB}
    depends_on:
      - userdb

  userdb:
    image: postgres
    container_name: userdb
    restart: always
    ports:
      - 8889:5433
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${USER_DB}
      POSTGRES_PASSWORD: ${PASSWORD_DB}
      POSTGRES_DB: ${NAME_DB}

networks:
  app_network:
    driver: bridge

volumes:
  postgres_data:
