server:
  port: 8083

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: "jdbc:postgresql://${HOST_DB}:${PORT_DB}/${NAME_DB}"
    username: ${USER_DB}
    password: ${PASSWORD_DB}
  liquibase:
    enabled: true
    change-log: db/changelog.yaml

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  application:
    name: USER-SERVICE
  config:
    import: configserver:http://localhost:9296
